.TH "GAMECAB" "1" "June 2023" "Metro Game Lab" "User Commands"
.SH "NAME"
gamecab \- free open source arcade cabinet emulation front end
.SH "SYNOPSIS"
gamecab
.SH "DESCRIPTION"
Metro Game Cabinet is a graphical front end for emulators, specifically designed for use in arcade cabinets. It allows you to select games via an intuitive, attractive interface which is easy to use with limited controls, such as a joystick. Gamecab is made available under the GNU General Public License Version 2, meaning anyone can freely download the source code and even contribute to development.
.PP
See http://www.metrogamelab.com/gamecab/ for help in configuration and usage.
